language: r

cache: packages

r_binary_packages:
    - covr
    - devtools
 
after_success:
  - Rscript -e 'library(covr); library(devtools); install_github("cdgreenidge/brcbase", ref = "kevin", overwrite = T); library(brcbase); codecov()'

warnings_are_errors: true
